#!/bin/bash

RETRY_COUNT=5
SLEEP=0.2

while [ $RETRY_COUNT -gt 0 ]; do
  if /sbin/drbdadm adjust $1; then
    /sbin/drbdadm wait-connect $1
    exit $?;
  fi
  let RETRY_COUNT--
  echo "fail to exec '/sbin/drbdadm adjust $1', retry $RETRY_COUNT, sleep $SLEEP second."
  sleep $SLEEP
done

echo "timeout during wait for /dev/drbdvg/$1"
exit 1
