---
- name: Build hosts file
  when: not hive_shared_repository is defined
  block:
  - name: "Build hosts file"
    become: True
    blockinfile:
      dest: /etc/hosts
      insertafter: BOF
      state: "present"
      block: "{{ hostvars[item].hive_private_ip }} {{ item }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    with_items: "{{ groups['servers'] | intersect(groups[hive_stage]) | list }}"

- name: Build hosts file for using shared repository
  when: hive_shared_repository is defined and inventory_hostname in groups['hives']
  block:
  - name: write hives ip
    become: True
    blockinfile:
      dest: /etc/hosts
      insertafter: BOF
      state: "present"
      block: "{{ hostvars[item].hive_private_ip }} {{ item }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
    with_items: "{{ groups['hives'] | intersect(groups[hive_stage]) | list }}"
  - name: write repository ip
    become: True
    blockinfile:
      dest: /etc/hosts
      insertafter: BOF
      state: "present"
      block: "{{ item }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.split(' ')[1] }}"
    when: item.split(' ')[1] in ( groups['repository'] | intersect(groups[hive_stage]) | list )
    loop: "{{ lookup('file', hive_shared_repository_path + '/hosts').splitlines() }}"