---
collections:
 - ansible.posix
 - name: ansible.netcommon
   version: 2.5.1
 - community.crypto
 - community.general
 - name: community.docker
   version: 2.2.1
 - community.zabbix
 - community.aws
 - amazon.aws
 - google.cloud
 - azure.azcollection
