---
collections:
 - ansible.posix
 - name: ansible.netcommon
   version: 2.5.1
 - community.crypto
 - community.general
 - name: community.docker
 - name: community.zabbix
   version: 1.8.0
 - community.aws
 - amazon.aws
 - google.cloud
 - azure.azcollection
