---
- name: put ssh_config
  blockinfile:
    dest: "{{ hive_context_dir }}/ssh_config"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ setup_host }}"
    state: present
    create: yes
    mode: 0644
    block: |
      Host {{ setup_host }}
        HostName {{ hostvars[setup_host].hive_private_ip }}
        UserKnownHostsFile {{ hive_context_dir }}/known_hosts
        StrictHostKeyChecking yes
        User {{ hostvars[setup_host].hive_safe_admin }}
        PasswordAuthentication no
        IdentityFile {{ hive_safe_private_key_path }}
        IdentitiesOnly yes
        LogLevel FATAL
      {% if hive_http_proxy is defined %}  RemoteForward {{ hive_http_proxy_port }} {{ hive_http_proxy }}{% endif %}
  loop: "{{ hive_safe_hosts }}"
  loop_control:
    loop_var: setup_host

