---
- name: reboot
  reboot:
    reboot_timeout: 300
  listen: require reboot
  when: not ansible_check_mode and not (inventory_hostname in groups['repository'] and hive_mother_repository is defined)
