---
- name: install CA cert files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/cacert.pem"
    dest:  /etc/ssl/certs/cacert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
- name: install built server cert files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/built-server-cert.pem"
    dest:  /etc/ssl/certs/built-server-cert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
- name: install built CA key files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/built-key.pem"
    dest:  /etc/ssl/certs/built-key.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
- name: install built csr files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/built.csr"
    dest:  /etc/ssl/certs/built.csr
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
- name: update trust store(alpine)
  shell: apk add --no-cache ca-certificates && update-ca-certificates
  when: 
    - ca_certs_alpine.changed 