---
- name: put CA cert files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/cacert.pem"
    dest:  /etc/ssl/certs/cacert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
- name: put server/client cert files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-server-cert.pem"
    dest:  /etc/ssl/certs/{{ item.certificate_fqdn }}-server-cert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
  loop: "{{ certificates }}"
- name: put server/client key files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-key.pem"
    dest:  /etc/ssl/certs/{{ item.certificate_fqdn }}-key.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
  loop: "{{ certificates }}"
- name: put server/client csr files(alpine)
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}.csr"
    dest:  /etc/ssl/certs/{{ item.certificate_fqdn }}.csr
    group: root
    owner: root
    mode: 0644
  register: ca_certs_alpine
  loop: "{{ certificates }}"
- name: update trust store(alpine)
  shell: apk add --no-cache ca-certificates && update-ca-certificates
  when: 
    - ca_certs_alpine.changed 