---
- name: make extra attributes file
  become: False
  delegate_to: "{{ groups['mother'] | intersect(groups[hive_stage]) | first }}"
  copy:
    src: extfile.cnf
    dest: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-extfile.cnf"
  loop: "{{ certificates }}"
- name: server/client CSR
  become: False
  delegate_to: "{{ groups['mother'] | intersect(groups[hive_stage]) | first }}"
  shell: |
    openssl req -batch -new -newkey rsa:4096 -nodes -sha256 \
      -subj '{{ item.sub_prefix }}/CN={{ item.certificate_fqdn }}' \
      -keyout {{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-key.pem \
      -out {{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}.csr
  args:
    creates: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}.csr"
  loop: "{{ certificates }}"
  
- name: server/client certificate
  become: False
  delegate_to: "{{ groups['mother'] | intersect(groups[hive_stage]) | first }}"
  shell: |
    openssl x509 -req  -days {{ item.ca_valid_in }} -sha256 -in {{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}.csr \
      -CAkey {{ hive_safe_ca_dir }}/cakey.pem \
      -CA {{ hive_safe_ca_dir }}/cacert.pem \
      -out {{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-server-cert.pem \
      -extfile {{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-extfile.cnf
  args:
    creates: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-server-cert.pem"
  loop: "{{ certificates }}"

- name: install server/client cert file
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-server-cert.pem"
    dest: "{{ item.cert_dest }}"
  loop: "{{ certificates }}"

- name: install server/client key file
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-key.pem"
    dest: "{{ item.key_dest }}"
  loop: "{{ certificates }}"