plugin: hive_inventory
name: pdns
stages:
  private:
    provider: vagrant
    separate_repository: False
    cidr: 192.168.0.96/27
    memory_size: 4096
    mirrored_disk_size: 10
    number_of_hosts: 1
  staging:
    provider: aws
    separate_repository: False
    cidr: 192.168.0.0/24
    instance_type: t3.medium
    region: ap-northeast-1
    mirrored_disk_size: 20
    repository_instance_type: t3.large
    subnets:
    - cidr: 192.168.0.0/26
      name: subnet-a
      available_zone: ap-northeast-1d
    - cidr: 192.168.0.64/26
      name: subnet-b
      available_zone: ap-northeast-1b
    - cidr: 192.168.0.128/26
      name: subnet-c
      available_zone: ap-northeast-1c
  production:
    provider: azure
    separate_repository: True
    cidr: 192.168.0.0/24
    instance_type: Standard_D2s_v3
    region: japaneast
    mirrored_disk_size: 20
    repository_instance_type: Standard_D2s_v3
  # production:
  #   provider: gcp
  #   separate_repository: True
  #   cidr: 192.168.0.0/24
  #   instance_type: n1-standard-2
  #   region: asia-northeast2
  #   mirrored_disk_size: 20
  #   repository_instance_type: n1-standard-2
