---
- name: install docker api and jinja2
  command:
    argv:
      - /usr/local/bin/python
      - -m
      - pip
      - install
      - docker
      - jinja2
      - six
- name: install configure
  copy: src=proxy-configure dest=/usr/sbin mode=0775
