---
- name: install CA cert files(centos)
  copy:
    src: "{{ hive_safe_ca_dir }}/cacert.pem"
    dest: /etc/pki/ca-trust/source/anchors/cacert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_centos
- name: install built server cert files(centos)
  copy:
    src: "{{ hive_safe_ca_dir }}/built-server-cert.pem"
    dest: /etc/pki/ca-trust/source/anchors/built-server-cert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_centos
- name: install built CA key files(centos)
  copy:
    src: "{{ hive_safe_ca_dir }}/built-key.pem"
    dest:  /etc/pki/ca-trust/source/anchors/built-key.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_centos
- name: install built csr files(centos)
  copy:
    src: "{{ hive_safe_ca_dir }}/built.csr"
    dest:  /etc/pki/ca-trust/source/anchors/built.csr
    group: root
    owner: root
    mode: 0644
  register: ca_certs_centos
- name: update trust store(centos)
  shell: update-ca-trust
  when: 
    - ca_certs_centos.changed 