name: release RC apps

on:
  push:
    branches-ignore:
      - '**'
    # prerelease only
    tags:
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install wheel
    - name: Build
      run: |
        poetry config repositories.test-pypi https://test.pypi.org/legacy/
        poetry config pypi-token.test-pypi "${{ secrets.TEST_PYPI_TOKEN }}"
        poetry build
        poetry publish -r test-pypi
