---
- name: install ca-certificates
  shell: apt-get update -y && apt-get install -y ca-certificates
- name: install CA cert files(ubuntu)
  copy:
    src: "{{ hive_safe_ca_dir }}/cacert.pem"
    dest: /etc/ssl/certs/cacert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_ubuntu
- name: install built server cert files(ubuntu)
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-server-cert.pem"
    dest: /etc/ssl/certs/{{ item.certificate_fqdn }}-server-cert.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_ubuntu
  loop: "{{ certificates }}"
- name: install built CA key files(ubuntu)
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}-key.pem"
    dest:  /etc/ssl/certs/{{ item.certificate_fqdn }}-key.pem
    group: root
    owner: root
    mode: 0644
  register: ca_certs_ubuntu
  loop: "{{ certificates }}"
- name: install built csr files(ubuntu)
  copy:
    src: "{{ hive_safe_ca_dir }}/{{ item.certificate_fqdn }}.csr"
    dest:  /etc/ssl/certs/{{ item.certificate_fqdn }}.csr
    group: root
    owner: root
    mode: 0644
  register: ca_certs_ubuntu
  loop: "{{ certificates }}"
- name: update trust store(ubuntu)
  shell: update-ca-certificates
  when: 
    - ca_certs_ubuntu.changed 